#!/usr/bin/env bash

# Take a screenshot
import -window root /tmp/lock_screen.png

# Pixellate it 10x
mogrify -scale 10% -scale 1000% /tmp/lock_screen.png

# Lock screen displaying this image.
i3lock -i /tmp/lock_screen.png

# Turn the screen off after a delay.
sleep 60; pgrep i3lock && xset dpms force off
